site: 'https://ddos-separ.ml'
meta: 
  - image: 'https://github.com/BogdanDevUA/simple-ddos/raw/master/meta/image.jpg'
  - description: 
    - google: 'Хакерська атака на сайти рф онлайн, без жодних навичок, Сайт для дудосу, IT Army of Ukraine, Зупинімо росію разом! І здохне путлєр'
    - og: '🇺🇦🌿 Проста хакерська атака на сайти рф! 👇'
    

scripts: 
  - 'dom.js'
  - 'scripts/random.js'
  - 'scripts/loader.js'
  - 'scripts/frame-manager.js'
  - 'scripts/worker.js'
  - 'scripts/functions.js'
  - 'scripts/main.js'